### PR TITLE
some more doc fixes

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by mintar** [comment]
There are three more dead links:

    URL        `../../Syskit/TaskContext.html'
    Name       `Syskit::TaskContext'
    Parent URL file:///home/martin/rock/base/doc/out/documentation/system/task_contexts.html, line 111, col 1
    Real URL   file:///home/martin/rock/base/doc/out/Syskit/TaskContext.html
    Check time 0.002 seconds
    Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/martin/rock/base/doc/out/Syskit/TaskContext.html'>
    
    URL        `../system/data_monitoring_tables.html'
    Name       `reference documentation'
    Parent URL file:///home/martin/rock/base/doc/out/documentation/system_management_tutorials/1200_data_monitors.html, line 130, col 1
    Real URL   file:///home/martin/rock/base/doc/out/documentation/system/data_monitoring_tables.html
    Check time 0.002 seconds
    Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/martin/rock/base/doc/out/documentation/system/data_monitoring_tables.html'>
    
    URL        `../system/fault_response_tables.html'
    Name       `in the documentation'
    Parent URL file:///home/martin/rock/base/doc/out/documentation/system_management_tutorials/1300_fault_response_tables.html, line 135, col 1
    Real URL   file:///home/martin/rock/base/doc/out/documentation/system/fault_response_tables.html
    Check time 0.002 seconds
    Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/martin/rock/base/doc/out/documentation/system/fault_response_tables.html'>

I couldn't find the pages they are supposed to be linking to, and I didn't feel comfortable just removing the links.

**Comment by mintar** [comment]
Did someone have time to look at this yet?

**Comment by doudou** [comment]
Unfortunately no. I'm going to merge this (looks like pretty nice grunt work, thanks !) but I don't really have time to look into the broken links

What do you use to check for broken links ???

**Comment by mintar** [comment]
Yes, it was a lot of grunt work. I stumbled across a couple of broken links and fenced code blocks and then got carried away and fixed all of them. :-)

To find the broken links, I ran linkchecker (via apt-get) in the `base/doc/out/` directory:

    find -name '*.html' -print0 | xargs -0 linkchecker -r1 --ignore-url='.*doc/out/(api|pkg|sets|tasks|types|osdeps|package_directory).*|^file:///(api|pkg|sets|tasks|types|osdeps|package_directory).*'

Let's just merge this and ignore the remaining broken links for now.

**Comment by doudou** [comment]
Agreed

**Pull request merged**
