### PR TITLE
Add port_driven statements (transformer, aligner)

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by jmachowinski** [comment]
uhm, this would create a bad bevaviour

**Comment by mintar** [comment]
Care to elaborate?

**Comment by jmachowinski** [comment]
if you are not port driven on dynamic_transformations (auto generated port) data will queue up and might get lost

**Comment by mintar** [comment]
So I should add dynamic_transformations to the port_driven statement? Without a port_driven statement (like it was before) it won't work at all, obviously.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jmachowinski** [comment]
either that, or not specify a port at all

**Comment by mintar** [comment]
Fixed.

**Comment by mintar** [comment]
Opened a new PR, since this one is already merged: #45 .

**Pull request merged**
